sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - REGISTRY_USER=vektory79
    - secure: gj/YYiyXHCWI5rbiIAM7eGe9/ZzlEBvcEB38i67pDo8ASR+sMwTwaTYEa0rUnaTL3lYdHOTP/F5xC6P62Gsnc2nX4/9ACJRowElbq/2KG5VENPMywG6y85zdTaurlLa9mac+9aJSM6UsAKjXgD2mMtF7ibw9Mf2bSGR+dPPMcV0XAqdRSMALVPVIR7ZtOpLltyySHND823G0fyZ1QtFQ46HgYRdciXTqriwREQp8Kj0S/Z8fdr/0AMC/hNwYRjIdLzXoCQSGegx18Bko2U3BUIZHedf0oTTqH0DGZxEksmyigWvLs7xb7gKNWhaYXS1nTzoo4nMXotv6vcR5bd1O9uggOiFJo+q1MX2bOJaVph8j8iNt6jeuzaqQp2AUyUY9hvTUuYXG1KMmOF/y3jvvkuZeRxK0paobE8aM4q5edOOlA5RjhpnD8jc570CjYQi3nzl/C+i+vSYuqQOXgwgNdDlcFM4tfMeZWaIc2XmNBVqGhZvSwT+U85oFTlx4VWRZ0MJBE7G9kWY/aR4vz17YYhC5Z1VSS1PBGR+b0vNcoO/z52VMIOoj9krTQTVwZdmsT+n/bsRqB9j4PSKmdYQnF75wN5j+6XcYh2a3faSOZFeRrDFQwGRnErjSlkElIWy3lUJ95/BfW7LhmBromyGvIYRv+MUr5QwkxeeTFJqKJv4=
script:
  - ./build.sh -pc

after_script:
  - docker images
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" vektory79-docker-docker.bintray.io

deploy:
  provider: script
  script: ./build.sh -rdc
  on:
    branch: master
